import * as authSchema from "./auth.schema"; // Generated by `pnpm auth:generate`

// Combine all schemas here for migrations. Add your own feature schemas
// as you create them (e.g. `import * as notesSchema from "./notes.schema"`).
export const schema = {
    ...authSchema,
} as const;
